apiVersion: v1
kind: Service
metadata:
  name: makepost-service
spec:
  selector:
    app: makepost
  ports:
    - protocol: TCP
      port: 6001
      targetPort: 6001
  type: LoadBalancer  # Expose the service externally
