apiVersion: v1
kind: Service
metadata:
  name: readpost-service
spec:
  selector:
    app: readpost
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000
  type: LoadBalancer  # Expose the service externally
